### ISSUE TITLE
listar Projetos

### ISSUE THREAD

**Issue by OrlandoEduardo101** [f-teamdev/ship#15]
<h3><strong>3.4.4. Listagem de Projetos:</strong></h3><h4><strong>			</strong>3.4.4.1. Usuários com as devidas permissões podem consultar a listagem de todos os projetos, de usuários relacionados ao projeto e das horas trabalhadas em cada projeto.</h4><p>			3.4.4.2. Usuários com as devidas permissões podem gerar relatórios relacionados aos projetos. </p>

**Comment by tauamendonca** [comment]
Aguarda resolução das issues #36  e #37
