### ISSUE TITLE
Backend - Erro 500 ao cadastrar dar update em um usuário com um valor diferente de null em "imageUrl"

### ISSUE THREAD

**Issue by ericqueirozc** [f-teamdev/ship#22]
Ao passar uma String ao invés de null em "imageUrl" na rota put '/user' a api retorna um erro 500 sem indicar o que exatamente deu errado. As vezes fala que a response não é do tipo Json e que deveria ser mudado no Response Type, as vezes erro de XML alguma coisa assim.

**Comment by ericqueirozc** [comment]
Exemplo que causa erro
![image](https://user-images.githubusercontent.com/51865318/187269999-080f83cd-5ed1-4519-a200-31a93936deeb.png)

**Comment by ericqueirozc** [comment]
String com link de imagem
![image](https://user-images.githubusercontent.com/51865318/187270452-f0d2d755-e5f5-47bf-802b-ab36f3ffb68a.png)

**Comment by ericqueirozc** [comment]
Com imageUrl null
![image](https://user-images.githubusercontent.com/51865318/187270679-faa3c939-1ec8-4ca7-ad73-102ca74d79c0.png)

**Comment by jacobaraujo7** [comment]
fixed
