### ISSUE TITLE
Erro 500 ao tentar fazer o update de um Cliente.

### ISSUE THREAD

**Issue by ericqueirozc** [f-teamdev/ship#30]
Enviado:

curl -X 'PUT' \
  'https://dev.shipstore.info/client' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI0MDkwNTUsImF1ZCI6ImFjY2Vzc1Rva2VuIiwiaWQiOjEsInJvbGUiOiJhZG1pbiJ9.t_5R0FAwJYTpd-az_6U1dOKcOd54NT6Euw-WjbZq8gQ' \
  -H 'Content-Type: application/json' \
  -d '{
    "id": 2,
    "name": "ATEAM DESENVOLVIMENTO DE SOFTWARE",
    "createdAt": "2022-09-01T22:00:21.921Z",
    "cnpj": "38025846000159",
    "address": "Jardim Paris, Rua Pioneiro Anibal Borin 441",
    "city": "Maringá",
    "country": "Brasil",
    "state": "Paraná",
    "imageUrl": null,
    "active": true
  }'

Recebido:

can't parse JSON.  Raw result:

type '_OneByteString' is not a subtype of type 'int?'/n#0      new UpdateClientParams.fromJson (package:backend/src/modules/client/domain/usecases/update_client.dart:70)
#1      ClientResource._update (package:backend/src/modules/client/presenter/client_resource.dart:48)
#2      applyHandler (package:shelf_modular/src/presenter/utils/handlers.dart:65)
#3      ModularBase._routeSuccess.<anonymous closure> (package:shelf_modular/src/presenter/modular_base.dart:186)
#4      ModularBase._routeSuccess.<anonymous closure> (package:shelf_modular/src/presenter/modular_base.dart:185)
#5      AuthGuard.call.<anonymous closure>.<anonymous closure> (package:backend/src/modules/auth/presenter/guards/auth_guard.dart:39)
#6      Right.match (package:fpdart/src/either.dart:343)
#7      Either.fold (package:fpdart/src/either.dart:227)
#8      AuthGuard.call.<anonymous closure> (package:backend/src/modules/auth/presenter/guards/auth_guard.dart:34)
<asynchronous suspension>
#9      ModularBase.handler (package:shelf_modular/src/presenter/modular_base.dart:150)
<asynchronous suspension>
#10     jsonEncoder.<anonymous closure>.<anonymous closure> (package:backend/backend.dart:42)
<asynchronous suspension>
#11     logRequests.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware/logger.dart:30)
<asynchronous suspension>

**Comment by jacobaraujo7** [comment]
Fixed. 
Verifica se foi corrigido, dai vc pode fechar essa issue se tudo estiver bem.

**Comment by ericqueirozc** [comment]
O problema foi corrigido!
