### ISSUE TITLE
Atualizar clientes

### ISSUE THREAD

**Issue by OrlandoEduardo101** [f-teamdev/ship#7]
<h4>3.2.1.1. Usuários com as devidas permissões podem cadastrar clientes; Entende-se como cliente para fins deste projeto todas as empresas e pessoas físicas que contratarem os serviços da empresa solicitante. <br/>3.2.1.2. Os clientes terão os campos Nome, id, Data de criação, CNPJ, logradouro, cidade, país, URL de imagem, status de ativo ou inativo e uma referência para objetos do tipo projetos. </h4><p><br/></p>

**Comment by tauamendonca** [comment]
Closed on Pull Request #31
