### ISSUE TITLE
Cadastro de projetos

### ISSUE THREAD

**Issue by OrlandoEduardo101** [f-teamdev/ship#8]
<h3><strong>3.4.1. Cadastro de Projetos:</strong></h3><h4><strong>			</strong>3.4.1.1. Usuários com as devidas permissões podem cadastrar novos Projetos relacionados com clientes;<br/>			3.4.1.2. Os projetos terão os campos titulo, id, data de criação, descrição, URL de imagem, um campo para armazenar se está ativo ou não, id do cliente relacionado, lista de entidades que contém o id do projeto e de usuários relacionados ao projeto, entidade cliente relacionada pelo id; </h4><p><br/></p>

**Comment by tauamendonca** [comment]
Aguarda resolução das issues https://github.com/f-teamdev/ship/issues/36 e https://github.com/f-teamdev/ship/issues/37
